### ISSUE TITLE
Pyvirtualbench errors on Windows 10 x64

### ISSUE THREAD

**Issue by ejo4041** [armstrap/armstrap-pyvirtualbench#2]
I have tried to run the example after renaming my device to match the dio_exampl.py program.  Command line spits this out, but I have not found any solution to the problem yet, anyone else see this?
 
python dio_example.py
Traceback (most recent call last):
File "dio_example.py", line 42, in <module>
dio = virtualbench.acquire_digital_input_output(channels_to_write);
File "C:\Program Files\Python36\lib\pyvirtualbench.py", line 525, in acquire_digital_input_output
return self.DigitalInputOutput(self, lines, reset)
File "C:\Program Files\Python36\lib\pyvirtualbench.py", line 533, in __init__
status = self.nilcicapi.niVB_Dig_InitializeW(self.library_handle, c_wchar_p(self.lines), c_bool(reset), byref(self.instrument_handle))
OSError: exception: access violation reading 0x0000000010D98990
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "dio_example.py", line 53, in <module>
virtualbench.release()
File "C:\Program Files\Python36\lib\pyvirtualbench.py", line 381, in release
status = self.nilcicapi.niVB_Finalize(self.library_handle)
OSError: exception: access violation writing 0x0000000010D98998

**Comment by ah257** [comment]
I came across this same issue and found that using 32 bit Python instead of 64 bit solved it for me.
